### ISSUE TITLE
History navigation is broken after one use

### ISSUE THREAD

**Issue by mattrossman** [videlais/snowman#198]
My understanding is that snowman uses the browser history to facilitate going forward/backward between passage choices.

However it seems to be broken. Using snowman 2.0.2 in Twine, after pressing the browser back button once, further navigation doesn't work. E.g.

1. Open story
2. Click link 1
3. Press browser back button
4. Click link 2
5. Press browser back button again

The result is that the page is destroyed, but it should take you back to the story start. This occurs for me in the latest Firefox and Chrome.

**Comment by mangoducksparkles** [comment]
I don't think there's a workaround for you; I think the source code needs to be updated.

I think this has to do with the `story.start()` and `story.show()` functions. The `story.show()` function sets `story.atCheckpoint = false`, which prevents the state being pushed to the history. Now, `story.start()` manually sets `story.atCheckpoint = true` after showing the first passage, so the state gets pushed to the history when you navigate away from the first passage. However, the `popstate` event listener (that triggers when you hit the back button) calls `story.show()`, but doesn't manually set `story.atCheckpoint = true` afterward. So, when you hit back to go to the first passage again, the `story.atCheckpoint` is reset to false, so the state isn't pushed to the history when you navigate away for the second time.

The fix seems simple (just add a `this.atCheckpoint = true;` to the `popstate` listener), but it's been forever since I've used git, and I never understood it much at all. It's nearly 3am, so I'll look into suggesting a change tomorrow.

**Comment by mangoducksparkles** [comment]
Oh, duh! I must've been super sleepy. Of course there's a workaround. Just add `<% story.checkpoint(); %>` to your starting passage. I just tested it, and it works for me.

**Comment by videlais** [comment]
The entire history system has been re-written to avoid these issues. This is no longer a problem with Snowman 2.2.
