### ISSUE TITLE
Global callbacks on snowman standard events don't work in 2.2.0

### ISSUE THREAD

**Issue by jenkin** [videlais/snowman#509]
I defined a custom callback on events such as `sm.story.started` following the [official documentation](https://videlais.github.io/snowman/2/events/story_events.html), it works fine in Twine built-in version of Snowman (2.0.3), but it never runs in 2.2.0 installed via [github](https://videlais.github.io/snowman/builds/2.2/format.js).

Am I missing anything?

**Comment by videlais** [comment]
As I mentioned over on [a post on the IntFiction forum](https://intfiction.org/t/snowman-2-2-preview-available/56718), the documentation is not accurate for Snowman 2.2. I am in the process of re-building all of it because I no longer have the original source files and the tool used to create it is no longer being updated. The new documentation should go up early next week.

The previous event `sm.story.started` is now simply `start`. An example might look like the following:

```
:: StoryTitle
Snowman 2: Start Event

:: UserScript[script]
/*
  When 'start' happens, overwrite current contents.

  This will only run once, as 'start' is only emitted
   at the beginning of a story.
*/
State.events.on('start', (passageName) => {
		let headerContent = Story.include("Header");
		let currentContent = Story.include(passageName);
		let footerContent = Story.include("Footer");
		$('tw-passage').html(headerContent + currentContent + footerContent);
});

:: Start
<p>[[Another Passage]]</p>

:: Another Passage
[[Back to beginning->Start]]

:: Header
This is the header!

:: Footer
This is the footer!

```

**Comment by jenkin** [comment]
Thank you very much, now I also read your post on IntFiction forum.

Using `State.events.on("start", ...)` or `State.events.on("show", ...)` it works, but I noticed in first passage the latter runs before the former. Is it an intended behaviour? I think it's a bit counter intuitive...

**Comment by videlais** [comment]
Good catch. The intended behavior is that `start` runs only once and `show` runs every time a reader navigates to another passage or the author calls `Story.show()`. I've now changed how `start()` works to make that more explicit. I will update the build as part of a process of updating the documentation soon.
